import json
import logging

import hapiserver

logger = logging.getLogger(__name__)


def app(config):
  """Create FastAPI HAPI server app using OpenAPI configuration.

  Note that hapiserver/openapi.json contains part of the OpenAPI specification
  for the server. The rest is generated by FastAPI based on the endpoints
  defined in app.py. Ideally, the full OpenAPI spec would be used to initialize
  the endpoints, but this is not trivial because of the decorators. We could
  use code a generation template, but this introduces complexity and difficultly
  with debugging.

  Args:
      config (str or dict): Configuration for the HAPI server. Can be a path to a JSON file or a dictionary.

  Returns:
      fastapi.FastAPI: The FastAPI app instance.
  """

  import fastapi

  logger.debug(f"app() called with config: {config}")
  config = hapiserver.config(config)

  logger.debug("Initalizing endpoints /docs and /openapi.json")
  app_kwargs = hapiserver.openapi.kwargs(['info'])
  app_kwargs['version'] = hapiserver.__version__

  logger.debug(f"Creating FastAPI app with {app_kwargs}")

  # See https://blog.stackademic.com/customizing-documentation-in-fastapi-24ee9f048e31
  # for customizing FastAPI docs.
  # TODO: Use css to hide redirect and head sections.
  app = fastapi.FastAPI(**app_kwargs)

  # Get the base path for the HAPI server.
  patho = config.get("path", "/hapi").rstrip("/")

  if not patho.endswith("hapi"):
    emsg = f"config.path = '{patho}' does not end with 'hapi'"
    logger.error(emsg)
    exit(1)

  _init_head(app, patho)
  _init_redirects(app, patho)
  _init_get(app, patho, config)

  return app


def _init_get(app, patho, config):
  import fastapi

  path = patho
  root_get_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi", 'get'])
  logger.debug(f"Initalizing GET endpoint {path} with {root_get_kwargs}")
  @app.get(path, response_class=fastapi.responses.HTMLResponse, **root_get_kwargs)
  def indexhtml(request: fastapi.Request):
    response = _hapi(config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/about"
  logger.info(f"Initalizing endpoint {path}/")
  about_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/about", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **about_kwargs)
  def about(request: fastapi.Request):
    response = _about(config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/capabilities"
  logger.info(f"Initalizing endpoint {path}/")
  capabilities_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/capabilities", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **capabilities_kwargs)
  def capabilities(request: fastapi.Request):
    response = _capabilities(config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/catalog"
  logger.info(f"Initalizing endpoint {path}/")
  catalog_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/catalog", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **catalog_kwargs)
  def catalog(request: fastapi.Request):
    response = _catalog(request.query_params, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/info"
  logger.info(f"Initalizing endpoint {path}/")
  info_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/info", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **info_kwargs)
  def info(request: fastapi.Request):
    response = _info(request.query_params, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/data"
  logger.info(f"Initalizing endpoint {path}/")
  data_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/data", 'get'])
  @app.get(path, **data_kwargs)
  def data(request: fastapi.Request):
    response = _data(request.query_params, config)
    if response.get('status_code', 200) != 200:
      return fastapi.responses.Response(**response)

    if isinstance(response['content'], str):
      return fastapi.responses.Response(**response)
    else:
      stream = response['content']
      del response['content']
      return fastapi.responses.StreamingResponse(stream, **response)


def _init_head(app, patho):
  import fastapi
  def head_kwargs(path):
    path = path.lstrip("/")
    summary = f"HEAD request for '{path}'"
    kwargs = {
      "tags": ["HEAD"],
      "status_code": 200,
      "summary": summary,
      "response_class": fastapi.responses.PlainTextResponse

    }
    logger.debug(f"Initalizing HEAD endpoint {path} with {kwargs}")
    return kwargs

  response = fastapi.responses.Response(status_code=200, content='')

  # Initialize landing page at {patho}/hapi
  path = patho
  @app.head(path, **head_kwargs(path))
  def indexhtml_head(request: fastapi.Request):
    return response

  # Initialize {patho}/about
  path = f"{patho}/about"
  @app.head(path, **head_kwargs(path))
  def about_head(request: fastapi.Request):
    return response

  # Initialize {patho}/catalog
  path = f"{patho}/catalog"
  @app.head(path, **head_kwargs(path))
  def catalog_head(request: fastapi.Request):
    return response

  # Initialize {patho}/info
  path = f"{patho}/info"
  @app.head(path, **head_kwargs(path))
  def info_head(request: fastapi.Request):
    return response

  # Initialize {patho}/data
  path = f"{patho}/data"
  @app.head(path, **head_kwargs(path))
  def data_head(request: fastapi.Request):
    return response


def _init_redirects(app, patho):
  import fastapi

  def redirect_kwargs(path):
    # Redirect, endpoints with trailing slash to endpoint without trailing slash.
    status_code = 301
    path_to = path.rstrip("/")
    summary = f"redirect of '{path}' to '{path_to}'"
    kwargs = {
      "status_code": status_code,
      "tags": ["Redirect"],
      "summary": summary,
      "responses": {
        status_code: {
          "description": f"HTTP {status_code} {summary}"
        }
      }
    }
    logger.debug(f"Initalizing {summary} with {kwargs}")
    return kwargs


  def response(path, request):
    qs = request.url.query
    url = path.rstrip("/")
    if qs:
      url = f"{url}?{qs}"
    return fastapi.responses.RedirectResponse(url=url, status_code=301)


  # Redirect "{patho}/" to "{patho}"
  path = f"{patho}/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def root_redirect(request: fastapi.Request, _path=path):
    return response(_path, request)

  # Redirect "{patho}/hapi/about/" to "{patho}/hapi/about"
  path = "/hapi/about/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def about_redirect(request: fastapi.Request, _path=path):
    return response(_path, request)

  path = "/hapi/catalog/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def catalog_redirect(request: fastapi.Request, _path=path):
    return response(_path, request)

  path = "/hapi/info/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def info_redirect(request: fastapi.Request, _path=path):
    return response(_path, request)

  path = "/hapi/data/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def data_redirect(request: fastapi.Request, _path=path):
    return response(_path, request)


def _query_params_dict(query_params):
  """Convert Starlette QueryParams to a plain dict.

  Args:
    query_params: Starlette QueryParams object

  Returns:
    dict: Plain dictionary with query parameter keys and values
  """

  if isinstance(query_params, dict):
    return query_params

  result = {}
  for key in query_params.keys():
    values = query_params.getlist(key)
    if len(values) == 1:
      result[key] = values[0]
    else:
      result[key] = values

  return result


def _query_param_error(endpoint, query):

  logger.debug("_query_param_error(): Checking query parameters.")

  if endpoint == 'catalog':
    allowed = []
    required = []

  if endpoint == 'info':
    allowed = ["dataset"]
    required = ["dataset"]

  if endpoint == 'data':
    allowed = ["dataset", "start", "stop", "parameters"]
    required = ["dataset", "start", "stop"]

  for p in query:
    if p not in allowed and not p.startswith('x_'):
      return {
        "code": 1401,
        "message_console": f"info(): Unknown query parameter '{p}'"
      }

  for p in required:
    if p not in query:
      return {
        "code": 1400,
        "message": f"Missing '{p}' parameter"
      }

  return None


def _call(endpoint, query_params, config):
  import hapiserver

  logger.debug(f"/{endpoint} query str:  '{query_params}'")
  query = _query_params_dict(query_params)
  logger.debug(f"/{endpoint} query dict: {query}")

  error = _query_param_error(endpoint, query)
  if error:
    logger.debug(f"_query_param_error() returned error: {error}")
    return None, error

  args = {}
  if endpoint == 'info':
    dataset, error = _get('dataset', query, config)
    args = {"dataset": dataset}
    if error:
      logger.debug(f"_get() returned error: {error}")
      return None, error

  if endpoint == 'data':
    args = {}
    for p in ['dataset', 'start', 'stop', 'parameters']:
      args[p], error = _get(p, query, config)
      if error:
        return hapiserver.error(error, config)

  if 'scripts' in config and endpoint in config['scripts']:

    args = [f"'{args[x]}'" for x in args.keys()]
    args = " ".join(args)

    if len(args) > 0:
      data, error = hapiserver.exec(config["scripts"][endpoint], args=args)
    else:
      data, error = hapiserver.exec(config["scripts"][endpoint])
    if error:
      message = "Script returned error"
      error = {
        "code": 1500,
        "message": message,
        "message_console": message,
        "exception": error
      }
      return None, error

    if endpoint == 'data':
      # For /data, the script is expected to return CSV data as a string.
      # Return directly in the response.
      return data, None

    try:
      data = json.loads(data)
    except Exception as e:
      message = f"Error parsing JSON returned by script: '{data}'"
      error = {
        "code": 1500,
        "message": message,
        "message_console": message,
        "exception": e
      }
      return None, error

    return data, None


  if 'functions' in config and endpoint in config['functions']:
    func = config['functions'][endpoint]
    logger.debug(f"Calling {func}({args})")
    try:
      args = [str(args[x]) for x in args.keys()]
      if len(args) > 0:
        data = func(*args)
      else:
        data = func()
    except Exception as e:
      message = f"Error executing {endpoint} function"
      error = {
        "code": 1500,
        "message": message,
        "message_console": message,
        "exception": e
      }
      logger.debug(f"Error executing {endpoint} function: {e}")
      return None, error

    return data, None

  return None, {
    "code": 1500,
    "message": f"No script or function configured for endpoint '{endpoint}'"
  }


def _headers(config, cors=True):
  server = f"HAPI/{hapiserver.HAPI_VERSION} Server"
  server += ";https://github.com/hapi-server/server-python-general"
  server += f"; v{hapiserver.__version__}"
  headers = {"Server": server}
  if cors:
    headers.update({
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "*",
      "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
    })
  return headers


def _get(name, query, config):

  import json

  if name == 'dataset':
    response = _catalog({}, config)
    if response.get('status_code', 200) != 200:
      return None, {"code": response.get('status_code', 1500), "message": "Failed to get catalog"}

    try:
      datasets = json.loads(response['content'])['catalog']
    except Exception as e:
      error = {
        "code": 1500,
        "message_console": f"_get(): Error parsing catalog JSON: {e}"
      }
      return None, error

    dataset_ids = [dataset['id'] for dataset in datasets]
    if query['dataset'] not in dataset_ids:
      error = {
        "code": 1407,
        "message_console": f"_get(): dataset '{query['dataset']}' not found in catalog"
      }
      return None, error

    return query['dataset'], None


  # TODO: Validate start/stop
  if name == 'start':
    return query['start'], None

  if name == 'stop':
    return query['stop'], None

  if name == 'parameters':

    if 'parameters' not in query:
      return '', None
    parameters = query['parameters']
    if parameters is None:
      return '', None
    if parameters == '':
      return '', None

    response = _info({'dataset': query['dataset']}, config)
    if response.get('status_code', 200) != 200:
      return None, {"code": response.get('status_code', 1500), "message": "Failed to get info"}

    try:
      info = json.loads(response['content'])
    except Exception as e:
      error = {
        "code": 1500,
        "message_console": f"_get(): Error parsing info JSON: {e}"
      }
      return None, error


    parameters_known = []
    if parameters:
      parameters_known = [p['name'] for p in info.get('parameters', [])]

    for p in parameters.split(","):
      if p not in parameters_known:
        error = {
          "code": 1407,
          "message_console": f"data(): Unknown parameter '{p}'"
        }
        return None, error

    return parameters, None


# Endpoint response functions
def _hapi(config):
  # TODO: This silently ignores any query parameters
  import os

  default = os.path.normpath(os.path.join(os.path.dirname(__file__)))
  default = os.path.join(default, "..", "html", "index.html")
  fname = config.get("index.html", None)
  if fname is None:
    logger.debug(f"No index.html configured, using default: {default}")
    fname = default

  logger.debug("Reading: " + fname)
  try:
    with open(fname) as f:
      content = f.read()
      response = {
        "status_code": 200,
        "content": content,
      }
  except Exception as e:
    logger.error(f"Error reading {fname}: {e}")
    response = {
      "status_code": 404,
      "content": "Not Found",
    }

  response['headers'] = _headers(config, cors=False)
  response['media_type'] = "text/html"
  return response


def _about(config):
  import json
  content = {
    "HAPI": hapiserver.HAPI_VERSION,
    "status": {
      "code": 1200, "message": "OK"
    },
    **config['about']
  }
  return {
    "content": json.dumps(content, indent=2),
    "media_type": "application/json",
    "headers": _headers(config),
  }


def _capabilities(config):
  import json
  content = {
    "HAPI": hapiserver.HAPI_VERSION,
    "status": {
      "code": 1200,
      "message": "OK"
    },
    **config.get('capabilities', {"outputFormats": ["csv"]})
  }
  return {
    "content": json.dumps(content, indent=2),
    "media_type": "application/json",
    "headers": _headers(config),
  }


def _catalog(query_params, config):

  catalog, error = _call('catalog', query_params, config)

  if error:
    return hapiserver.error(error, config)

  content = {
    "HAPI": hapiserver.HAPI_VERSION,
    "status": {
      "code": 1200,
      "message": "OK"
    },
    "catalog": catalog
  }

  response = {
    "content": json.dumps(content, indent=2),
    "media_type": "application/json",
    "headers": _headers(config),
  }

  return response


def _info(query_params, config):

  info, error = _call('info', query_params, config)
  if error:
    return hapiserver.error(error, config)

  if isinstance(info, str):
    info = json.loads(info)

  content = {
    "HAPI": hapiserver.HAPI_VERSION,
    "status": {
      "code": 1200,
      "message": "OK"
    },
    **info
  }

  return {
    "content": json.dumps(content, indent=2),
    "media_type": "application/json",
    "headers": _headers(config),
  }


def _data(query_params, config):

  data, error = _call('data', query_params, config)
  if error:
    return hapiserver.error(error, config)

  print(data)

  response = {
    "content": data,
    "media_type": "text/csv",
    "headers": _headers(config),
  }

  return response

  logger.debug(f"/data request: {query_params}")
  query = _query_params_dict(query_params)
  logger.debug(f"/data request: {query}")

  error = _query_param_error('data', query)
  if error:
    return None, error

  for p in ['dataset', 'start', 'stop', 'parameters']:
    query[p], error = _get(p, query, config)
    if error:
      return hapiserver.error(error, config)

  args = f"{query['dataset']} {query['start']} {query['stop']} {query['parameters']}"

  if 'scripts' in config:
    stream = config.get('stream', None)
    stdout, error = hapiserver.exec(config["scripts"]["data"], args, stream=stream)
    if error:
      return hapiserver.error(error, config)


  response = {
    "content": stdout,
    "media_type": "text/csv",
    "headers": _headers(config),
  }

  return response
