import logging

import hapiserver

logger = logging.getLogger(__name__)


def app(config):
  """Create FastAPI HAPI server app using OpenAPI configuration.

  Note that hapiserver/openapi.json contains part of the OpenAPI specification
  for the server. The rest is generated by FastAPI based on the endpoints
  defined in app.py. Ideally, the full OpenAPI spec would be used to initialize
  the endpoints, but this is not trivial because of the decorators. We could
  use code a generation template, but this introduces complexity and difficultly
  with debugging.

  Args:
      config (str or dict): Configuration for the HAPI server. Can be a path to a JSON file or a dictionary.

  Returns:
      fastapi.FastAPI: The FastAPI app instance.
  """

  import fastapi

  logger.debug(f"app() called with config: {config}")
  config = hapiserver.config(config)

  logger.debug("Initalizing endpoints /docs and /openapi.json")
  app_kwargs = hapiserver.openapi.kwargs(['info'])
  app_kwargs['version'] = hapiserver.__version__

  logger.debug(f"Creating FastAPI app with {app_kwargs}")

  # See https://blog.stackademic.com/customizing-documentation-in-fastapi-24ee9f048e31
  # for customizing FastAPI docs.
  # TODO: Use css to hide redirect and head sections.
  app = fastapi.FastAPI(**app_kwargs)

  # Get the base path for the HAPI server.
  patho = config.get("path", "/hapi").rstrip("/")

  if not patho.endswith("hapi"):
    emsg = f"config.path = '{patho}' does not end with 'hapi'"
    logger.error(emsg)
    exit(1)

  _init_head(app, patho)
  _init_redirects(app, patho)
  _init_get(app, patho, config)

  return app


def _log_request(endpoint_name, request):
  logger.info(f"{endpoint_name} called with {request.query_params}")


def _init_get(app, patho, config):
  import fastapi

  path = patho

  root_get_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi", 'get'])
  logger.debug(f"Initalizing GET endpoint {path} with {root_get_kwargs}")
  @app.get(path, response_class=fastapi.responses.HTMLResponse, **root_get_kwargs)
  def indexhtml(request: fastapi.Request):
    _log_request(path, request)
    query = request.query_params.__dict__['_dict']
    response = hapiserver.endpoints.hapi(query, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/about"
  logger.info(f"Initalizing endpoint {path}/")
  about_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/about", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **about_kwargs)
  def about(request: fastapi.Request):
    _log_request(path, request)
    query = request.query_params.__dict__['_dict']
    response = hapiserver.endpoints.about(query, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/capabilities"
  logger.info(f"Initalizing endpoint {path}/")
  capabilities_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/capabilities", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **capabilities_kwargs)
  def capabilities(request: fastapi.Request):
    _log_request(path, request)
    query = request.query_params.__dict__['_dict']
    response = hapiserver.endpoints.capabilities(query, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/catalog"
  logger.info(f"Initalizing endpoint {path}/")
  catalog_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/catalog", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **catalog_kwargs)
  def catalog(request: fastapi.Request):
    _log_request(path, request)
    query = request.query_params.__dict__['_dict']
    response = hapiserver.endpoints.catalog(query, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/info"
  logger.info(f"Initalizing endpoint {path}/")
  info_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/info", 'get'])
  @app.get(path, response_class=fastapi.responses.JSONResponse, **info_kwargs)
  def info(request: fastapi.Request):
    _log_request(path, request)
    query = request.query_params.__dict__['_dict']
    response = hapiserver.endpoints.info(query, config)
    return fastapi.responses.Response(**response)


  path = f"{patho}/data"
  logger.info(f"Initalizing endpoint {path}/")
  data_kwargs = hapiserver.openapi.kwargs(['paths', "/hapi/data", 'get'])
  @app.get(path, **data_kwargs)
  def data(request: fastapi.Request):
    _log_request(path, request)
    query = request.query_params.__dict__['_dict']
    response = hapiserver.endpoints.data(query, config)
    if response.get('status_code', 200) != 200:
      return fastapi.responses.Response(**response)

    if isinstance(response['content'], str):
      return fastapi.responses.Response(**response)
    else:
      stream = response['content']
      del response['content']
      return fastapi.responses.StreamingResponse(stream, **response)


def _init_head(app, patho):
  import fastapi

  def head_kwargs(path):
    path = path.lstrip("/")
    summary = f"HEAD request for '{path}'"
    kwargs = {
      "tags": ["HEAD"],
      "status_code": 200,
      "summary": summary,
      "response_class": fastapi.responses.PlainTextResponse

    }
    logger.debug(f"Initalizing HEAD endpoint {path} with {kwargs}")
    return kwargs

  response = fastapi.responses.Response(status_code=200, content='')

  # Initialize landing page at {patho}/hapi
  path = patho
  @app.head(path, **head_kwargs(path))
  def indexhtml_head(request: fastapi.Request):
    _log_request(path, request)
    return response

  # Initialize {patho}/about
  path = f"{patho}/about"
  @app.head(path, **head_kwargs(path))
  def about_head(request: fastapi.Request):
    _log_request(path, request)
    return response

  # Initialize {patho}/catalog
  path = f"{patho}/catalog"
  @app.head(path, **head_kwargs(path))
  def catalog_head(request: fastapi.Request):
    _log_request(path, request)
    return response

  # Initialize {patho}/info
  path = f"{patho}/info"
  @app.head(path, **head_kwargs(path))
  def info_head(request: fastapi.Request):
    _log_request(path, request)
    return response

  # Initialize {patho}/data
  path = f"{patho}/data"
  @app.head(path, **head_kwargs(path))
  def data_head(request: fastapi.Request):
    _log_request(path, request)
    return response


def _init_redirects(app, patho):
  import fastapi

  def redirect_kwargs(path):
    # Redirect, endpoints with trailing slash to endpoint without trailing slash.
    status_code = 301
    path_to = path.rstrip("/")
    summary = f"redirect of '{path}' to '{path_to}'"
    kwargs = {
      "status_code": status_code,
      "tags": ["Redirect"],
      "summary": summary,
      "responses": {
        status_code: {
          "description": f"HTTP {status_code} {summary}"
        }
      }
    }
    logger.debug(f"Initalizing {summary} with {kwargs}")
    return kwargs


  def response(path, request):
    qs = request.url.query
    url = path.rstrip("/")
    if qs:
      url = f"{url}?{qs}"
    return fastapi.responses.RedirectResponse(url=url, status_code=301)


  # Redirect "{patho}/" to "{patho}"
  path = f"{patho}/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def root_redirect(request: fastapi.Request, _path=path):
    _log_request(_path, request)
    return response(_path, request)

  # Redirect "{patho}/hapi/about/" to "{patho}/hapi/about"
  path = "/hapi/about/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def about_redirect(request: fastapi.Request, _path=path):
    _log_request(_path, request)
    return response(_path, request)

  path = "/hapi/catalog/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def catalog_redirect(request: fastapi.Request, _path=path):
    _log_request(_path, request)
    return response(_path, request)

  path = "/hapi/info/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def info_redirect(request: fastapi.Request, _path=path):
    _log_request(_path, request)
    return response(_path, request)

  path = "/hapi/data/"
  kwargs = redirect_kwargs(path)
  @app.get(path, **kwargs)
  @app.head(path, **kwargs)
  def data_redirect(request: fastapi.Request, _path=path):
    _log_request(_path, request)
    return response(_path, request)
